# Generated by Django 5.2.6 on 2025-09-20 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Media',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='video',
            new_name='media',
        ),
    ]
