# Generated by Django 5.2.6 on 2025-09-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
