# Generated by Django 5.2.6 on 2025-09-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sign_up_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
