# Generated by Django 5.2.6 on 2025-09-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_sign_up_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_of_event',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
