[project]
name = "tech-builders"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.6",
    "django-browser-reload>=1.20.0",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.1.1",
]
