# Generated by Django 5.2.6 on 2025-09-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_instagram_url_user_linked_in_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='career',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
