# Generated by Django 5.2.6 on 2025-09-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityproject',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
