# Generated by Django 5.2.6 on 2025-09-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_projects', '0002_communityproject_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityproject',
            name='resources_needed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communityproject',
            name='sign_up_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
