# Generated by Django 5.2.6 on 2025-09-20 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creation',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.post')),
                ('demo', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Creation',
                'verbose_name_plural': 'Creations',
            },
            bases=('posts.post',),
        ),
    ]
