# Generated by Django 5.2.6 on 2025-09-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creation',
            name='area_of_focus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
